// <auto-generated />
using ContactManager.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactManager.Migrations
{
    [DbContext(typeof(ContactContext))]
    partial class ContactContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContactManager.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            Email = "james_hetfield@insideranken.org",
                            Firstname = "James",
                            Lastname = "Hetfield",
                            Phone = "1234567890"
                        },
                        new
                        {
                            ContactId = 2,
                            Email = "lars_ulrich@insideranken.org",
                            Firstname = "Lars",
                            Lastname = "Ulrich",
                            Phone = "0987654321"
                        },
                        new
                        {
                            ContactId = 3,
                            Email = "kirk_hammett@insideranken.org",
                            Firstname = "Kirk",
                            Lastname = "Hammett",
                            Phone = "1357924680"
                        },
                        new
                        {
                            ContactId = 4,
                            Email = "robert_trujillo@insideranken.org",
                            Firstname = "Robert",
                            Lastname = "Trujillo",
                            Phone = "2468013579"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
